#!/usr/bin/env python3
"""
Protocol Analyzer Template
Auto-generated by GlasseyeOS AI Tool Generator
Protocol: MCP
Target: github-api-demo
Message Format: JSON
Auth Method: None
Generated: 2026-05-18T17:22:56.549281
"""

import logging
import json
import sys
from typing import Dict, List, Optional
from datetime import datetime
from collections import defaultdict


class ProtocolAnalyzer:
    """
    Protocol traffic analyzer.
    Analyzes protocol messages for anomalies and patterns.
    """
    
    def __init__(self, protocol_name: str, verbose: bool = False):
        """
        Initialize protocol analyzer.
        
        Args:
            protocol_name: Name of protocol being analyzed
            verbose: Enable verbose logging
        """
        self.protocol_name = protocol_name
        self.verbose = verbose
        self.messages = []
        self.stats = defaultdict(int)
        self.setup_logging()
        
    def setup_logging(self):
        """Configure logging."""
        level = logging.DEBUG if self.verbose else logging.INFO
        logging.basicConfig(
            level=level,
            format='%(asctime)s - %(levelname)s - %(message)s'
        )
        self.logger = logging.getLogger('ProtocolAnalyzer')
        
    def capture_message(self, message: str, direction: str = 'incoming'):
        """
        Capture a protocol message for analysis.
        
        Args:
            message: Raw message content
            direction: 'incoming' or 'outgoing'
        """
        timestamp = datetime.now().isoformat()
        
        captured = {{
            'timestamp': timestamp,
            'direction': direction,
            'message': message,
            'size': len(message)
        }}
        
        self.messages.append(captured)
        self.stats[direction] += 1
        self.stats['total_bytes'] += len(message)
        
        self.logger.debug(f"Captured {{direction}} message: {{len(message)}} bytes")
        
    def parse_message(self, message: str) -> Dict:
        """
        Parse protocol message based on format.
        
        Args:
            message: Raw message string
            
        Returns:
            Parsed message dictionary
        """
        try:
            # For JSON-based protocols
            parsed = json.loads(message)
            return {{
                'valid': True,
                'format': 'JSON',
                'parsed': parsed,
                'fields': list(parsed.keys()) if isinstance(parsed, dict) else []
            }}
        except json.JSONDecodeError:
            # Try other formats or mark as unparseable
            return {{
                'valid': False,
                'format': 'Unknown',
                'raw': message[:100]
            }}
            
    def analyze_patterns(self) -> Dict:
        """
        Analyze captured messages for patterns.
        
        Returns:
            Analysis results dictionary
        """
        self.logger.info(f"Analyzing {{len(self.messages)}} messages")
        
        analysis = {{
            'total_messages': len(self.messages),
            'incoming': self.stats['incoming'],
            'outgoing': self.stats['outgoing'],
            'total_bytes': self.stats['total_bytes'],
            'avg_message_size': self.stats['total_bytes'] / len(self.messages) if self.messages else 0,
            'message_types': defaultdict(int),
            'anomalies': []
        }}
        
        # Analyze message types and detect anomalies
        for msg in self.messages:
            parsed = self.parse_message(msg['message'])
            
            if parsed['valid']:
                # Track message types
                if 'method' in parsed.get('parsed', {{}}):
                    method = parsed['parsed']['method']
                    analysis['message_types'][method] += 1
                    
            else:
                # Flag unparseable messages as anomalies
                analysis['anomalies'].append({{
                    'timestamp': msg['timestamp'],
                    'reason': 'unparseable',
                    'sample': msg['message'][:100]
                }})
                
        # Detect size anomalies
        sizes = [msg['size'] for msg in self.messages]
        if sizes:
            avg_size = sum(sizes) / len(sizes)
            for msg in self.messages:
                if msg['size'] > avg_size * 10:  # 10x larger than average
                    analysis['anomalies'].append({{
                        'timestamp': msg['timestamp'],
                        'reason': 'size_anomaly',
                        'size': msg['size'],
                        'avg_size': avg_size
                    }})
                    
        self.logger.info(f"Analysis complete: {{len(analysis['anomalies'])}} anomalies detected")
        
        return analysis
        
    def generate_report(self) -> str:
        """
        Generate analysis report.
        
        Returns:
            Formatted report string
        """
        analysis = self.analyze_patterns()
        
        report = f"""
{'='*60}
Protocol Analysis Report
{'='*60}
Protocol: MCP
Target: github-api-demo
Generated: {{datetime.now().isoformat()}}

MESSAGE STATISTICS
------------------
Total Messages: {{analysis['total_messages']}}
Incoming: {{analysis['incoming']}}
Outgoing: {{analysis['outgoing']}}
Total Bytes: {{analysis['total_bytes']}}
Average Size: {{analysis['avg_message_size']:.2f}} bytes

MESSAGE TYPES
-------------
"""
        
        for msg_type, count in analysis['message_types'].items():
            report += f"{{msg_type}}: {{count}}\n"
            
        report += f"""
ANOMALIES DETECTED
------------------
Total Anomalies: {{len(analysis['anomalies'])}}
"""
        
        for anomaly in analysis['anomalies'][:10]:  # Show first 10
            report += f"- {{anomaly['timestamp']}}: {{anomaly['reason']}}\n"
            
        report += f"\n{{'='*60}}\n"
        
        return report
        
    def save_capture(self, filename: str):
        """Save captured messages to file."""
        with open(filename, 'w') as f:
            json.dump(self.messages, f, indent=2)
            
        self.logger.info(f"Capture saved to {{filename}}")


def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Protocol Analyzer')
    parser.add_argument('--protocol', default='{MCP}', help='Protocol name')
    parser.add_argument('--capture-file', help='File containing captured messages')
    parser.add_argument('--output', default='analysis_report.txt', help='Output report file')
    parser.add_argument('--verbose', action='store_true', help='Verbose output')
    
    args = parser.parse_args()
    
    analyzer = ProtocolAnalyzer(args.protocol, args.verbose)
    
    # Load captured messages if provided
    if args.capture_file:
        with open(args.capture_file, 'r') as f:
            data = json.load(f)
            for msg_data in data:
                analyzer.capture_message(
                    msg_data.get('message', ''),
                    msg_data.get('direction', 'incoming')
                )
                
    # Generate and save report
    report = analyzer.generate_report()
    
    with open(args.output, 'w') as f:
        f.write(report)
        
    print(report)
    print(f"\nFull report saved to {{args.output}}")


if __name__ == '__main__':
    main()
